[RunControl]
EUDAQ_CTRL_PRODUCER_LAST_START = aida_tlu
EUDAQ_CTRL_PRODUCER_FIRST_STOP = aida_tlu

[Producer.altel]
EUDAQ_ID=50
EUDAQ_DC=one




[DataCollector.one]
EUDAQ_ID=1
EUDAQ_DATACOL_SEND_MONITOR_FRACTION=1
EUDAQ_FW=native
EUDAQ_FW_PATTERN=/home/user/workspace/altel_acts/RUN/eudaq/DATA/run$6R.raw
EUDAQ_MN=StdEventMonitor


